spring:
  data:
    cassandra:
      keyspace-name: oneviewdashboard
      contact-points: cassandra
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      password:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        ACCOUNT:
          destination: ACCOUNT
          contentType: application/json
        CREDIT_HISTORY:
          destination: CREDIT_HISTORY
          contentType: application/json